name: Terraform Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Terraform Format   
      uses: 'hashicorp/terraform:0.12.24'
      with:
        args: fmt -recursive -check
    - name: Terraform Init
      uses: 'hashicorp/terraform:0.12.24'
      with:
        args: init -backend=false
    - name: Terraform Validate
      uses: 'hashicorp/terraform:0.12.24'
      with:
        args: validate
